name: APEmoticons
main: apdevteam.APEmotes.APEmotes
version: 1.0
authors: [Foxtrot2400, cccm5]
commands:
   map:
      description: Provides you with a link to the AP Territory map
   apmap:
      description: Provides you with a link to the AP Territory map
   prices:
      description: Provides you with a link to the AP trading prices
   tradingprices:
      description: Provides you with a link to the AP trading prices
   emotes:
      description: General add, remove, and reload emotes command
      aliases: emote
     # usage: /emotes (add :emote: ASCII/remove :emote:/reload)
permissions:
   emote.edit:
      default: op
